name: airwave-airtime
services:
 backend: 
  build:
    context: ./backend
    # include the image 
    dockerfile: Dockerfile
  container_name: airwave_api
  environment:
    - NODE_ENV=development
    - PORT=8000
    - SERVER_URL=http://localhost
    - DB_USER=sa
    - DB_PASSWORD=Pass@2025!!
    - DB_DIALECT=mssql
    - DB_HOST=db
    - DB_NAME=Airwave-airtime-app-development
    - DB_PORT=1433
  depends_on:
    - db
  # command: [ "./wait-for", "db:1433", "--", "node ./index.js" ]
  ports:
    - 8000:8000
  networks:
    - app-net

  
 db:
    image: mcr.microsoft.com/mssql/server:2022-latest 
    container_name: mssql_db
    environment:
        - ACCEPT_EULA=Y
        - MSSQL_PID=Express
        - SA_PASSWORD=Pass@2025!!
   
    ports:
       - 1433:1433
    volumes:
       - mssql_data:/var/opt/mssql
    networks: 
       - app-net

 frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: airwave_web
    depends_on:
       - backend
    ports:
       - 3000:80
    networks:
       - app-net


volumes:
  mssql_data:
networks:
   app-net:
     driver: bridge
        
         